config/routes.rb
GreenFeather::Application.routes.draw do
  get "sites/photos"
  get "sites/booth"
  get "sites/edit"
  get "green_feather/index"

  root 'green_feather#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/green_feather_controller.rb
class GreenFeatherController < ApplicationController
  def index
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def photos
  end

  def booth
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/green_feather_helper.rb
module GreenFeatherHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/green_feather/index.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class=" js no-touch svg inlinesvg svgclippaths no-iecompat" lang="en" style>
    <!--<![endif]-->
    <head>
      <meta charset="utf-8">
    </head>
    <body>
        <div class="row">
          <div class="large-5 small-8 columns">
            <div class="card">
              <div class="container">
                <div class="front">
                    <%= image_tag "norris.jpg" %>
                </div>
                <div class="back">
                  <h5>Photography</h5>
                  <p>This card will be where customers can enter Greenfeather's photography page</p>
                    <%= link_to "Enter Photography", sites_photos_url, class: "fancy radius button" %>
                </div>
              </div>
            </div>
          </div>
          <div class="large-5 small-8 columns">
            <div class="card">
              <div class="container">
                <div class="front">
                    <%= image_tag "ace.jpg" %>
                </div>
                <div class="back">
                  <h5>Photobooth</h5>
                  <p>This card will be where customers can enter Greenfeather's photo booth rental page</p>
                    <%= link_to "Enter Photo Booth", sites_booth_url, class: "fancy radius button" %>
                </div>
              </div>
            </div>
          </div>
          <div class="large-5 small-8 columns">
            <div class="card">
              <div class="container">
                <div class="front">
                    <%= image_tag "robot.jpg" %>
                </div>
                <div class="back">
                  <h5>PhotoEditing</h5>
                  <p>This card will be where customers can have their person photos edited</p>
                    <%= link_to "Enter Photo Editing", sites_edit_url, class: "fancy radius button" %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </body>
</html>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Green Feather" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Green Feather" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!--<header>-->
      <!--<%= render 'layouts/navigation' %>-->
    <!--</header>-->
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/sites/booth.html.erb
<% provide(:title, 'GreenFeather Photo Booth') %>
<h1>Green Feather Photo Booths</h1>
<p>This will be the main site for photo booth rentals</p>

app/views/sites/edit.html.erb
<% provide(:title, 'GreenFeather Editing') %>
<h1>Green Feather Photo Editing</h1>
<p>This will be the main site were people can have their own photos edited for a charge.</p>

app/views/sites/photos.html.erb
<% provide(:title, 'GreenFeather Photography') %>
<!-- Requires Foundation 4 | visit http://foundation.zurb.com to download -->

<div class="row">
  <div class="large-12 columns">

    <!-- Navigation -->
    <nav class="top-bar">
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1>
            <a href="#">
              Top Bar Title
            </a>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="left">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
        </ul>

        <ul class="right">
          <li class="search">
            <form>
              <input type="search">
            </form>
          </li>

          <li class="has-button">
            <a class="small button" href="#">Search</a>
          </li>
        </ul>
      </section>
    </nav>

    <!-- End Navigation -->

  </div>
</div>


<div class="row">
  <div class="large-12 columns">

    <!-- Desktop Slider -->

    <div class="hide-for-small">
      <div id="featured">
        <img src="http://placehold.it/1500x400&text=Slide Image" alt="slide image">
        <!-- <img src="http://placehold.it/1000x400&text=Slide Image" alt="slide image">
        <img src="http://placehold.it/1000x400&text=Slide Image" alt="slide image"> -->
      </div>
    </div>

    <!-- End Desktop Slider -->


    <!-- Mobile Header -->


    <div class="row">
      <div class="small-12 show-for-small"><br>
        <img src="http://placehold.it/1000x600&text=For Small Screens" />
      </div>
    </div>


    <!-- End Mobile Header -->

  </div>
</div><br>

<div class="row">
  <div class="large-12 columns">
    <div class="row">

      <!-- Thumbnails -->

      <div class="large-3 small-6 columns">
        <img src="http://placehold.it/250x250&text=Thumbnail" />
        <h6 class="panel">Description</h6>
      </div>

      <div class="large-3 small-6 columns">
        <img src="http://placehold.it/250x250&text=Thumbnail" />
        <h6 class="panel">Description</h6>
      </div>

      <div class="large-3 small-6 columns">
        <img src="http://placehold.it/250x250&text=Thumbnail" />
        <h6 class="panel">Description</h6>
      </div>

      <div class="large-3 small-6 columns">
        <img src="http://placehold.it/250x250&text=Thumbnail" />
        <h6 class="panel">Description</h6>
      </div>

      <!-- End Thumbnails -->

    </div>
  </div>
</div>



<div class="row">
  <div class="large-12 columns">
    <div class="row">

      <!-- Content -->

      <div class="large-8 columns">
        <div class="panel radius">

          <div class="row">
            <div class="large-6 small-6 columns">

              <h4>Header</h4><hr/>
              <h5 class="subheader">Can put on text here if you want, just an idea!!
              </h5>

              <div class="show-for-small" align="center">
                <a href="#" class="small radius button">Call To Action!</a><br>

                <a href="#" class="small radius button">Call To Action!</a>
              </div>

            </div>
            <div class="large-6 small-6 columns">

              <p>Can put of info here about what you do, how cool and better you are over your competition!!!!
              </p>
            </div>

          </div>
        </div>
      </div>

      <div class="large-4 columns hide-for-small">

        <h4>Get In Touch!</h4><hr/>

        <a class="large button expand" href="#">
          Button to something!
        </a>

        <a class="large button expand" href="#">
          Another Button!
        </a>


      </div>

      <!-- End Content -->

    </div>
  </div>
</div>

<!-- Footer -->

<footer class="row">
  <div class="large-12 columns">
    <hr>
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; GreenFeather</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>